project_id = "dxdpdwwwhhwbbcybyshd"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.asaas-webhook]
    verify_jwt = false
